# Render.com Deployment Configuration - Jain Global Slack Trading Bot
# PostgreSQL-based deployment with required external APIs

services:
  - type: web
    name: jain-trading-bot
    env: python
    
    # Main application deployment
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    
    plan: free  # 100% FREE tier (750 hours/month)
    
    # Required environment variables
    envVars:
      - key: SLACK_BOT_TOKEN
        sync: false  # Set in dashboard: xoxb-your-bot-token
      - key: SLACK_SIGNING_SECRET
        sync: false  # Set in dashboard: your-signing-secret
      - key: FINNHUB_API_KEY
        sync: false  # Required: real market data
      - key: ALPACA_API_KEY
        sync: false  # Required: paper trading
      - key: ALPACA_SECRET_KEY
        sync: false  # Required: paper trading
      - key: DATABASE_URL
        fromDatabase:
          name: jain-trading-db
          property: connectionString
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 8080
      - key: HOST
        value: 0.0.0.0
      - key: REDIS_URL
        fromService:
          type: redis
          name: jain-trading-bot-redis
          property: connectionString
      - key: REDIS_ENABLED
        value: true
      - key: REDIS_TTL_SECONDS
        value: 300
      - key: APPROVED_CHANNELS
        value: C09H1R7KKP1,C09HFMTQYDU
      - key: SESSION_TIMEOUT_MINUTES
        value: 480
      - key: MAX_FAILED_ATTEMPTS
        value: 5
      - key: ALPACA_PAPER_API_KEY
        sync: false  # Set in dashboard: your paper API key
      - key: ALPACA_PAPER_SECRET_KEY
        sync: false  # Set in dashboard: your paper secret key
      - key: ALPACA_PAPER_BASE_URL
        value: https://paper-api.alpaca.markets
      - key: ALPACA_PAPER_ENABLED
        value: true
    
    # Health monitoring
    healthCheckPath: /health
    
    # Auto-deploy from main branch
    autoDeploy: true

# PostgreSQL database for persistent storage
databases:
  - name: jain-trading-db
    databaseName: trading_bot
    user: trading_user
    plan: free  # Free PostgreSQL (1GB storage)

# Redis cache for improved performance
services:
  - type: redis
    name: jain-trading-bot-redis
    plan: free  # Free Redis (0.25GB RAM)
    maxmemoryPolicy: allkeys-lru