# Render Blueprint for OMS API
# This file configures automatic deployment on Render

services:
  # PostgreSQL Database
  - type: pserv
    name: slackoms-db
    plan: free
    region: oregon
    databaseName: slackoms
    databaseUser: slackoms

  # OMS API Web Service
  - type: web
    name: slackoms-api
    runtime: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: OMS_API_KEY
        generateValue: true  # Auto-generate on first deploy
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: slackoms-db
          property: connectionString

